export const quartos = [
  {
    id: 101,
    nome: "Quarto Standard",
    descricao: "Quarto aconchegante com cama de casal e ar-condicionado. Ideal para casais.",
    preco: 180,
    tipo: "Standard",
    avaliacao: 8.7,
    imagem: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",
    comodidades: ["Wi-Fi", "Ar-condicionado", 'TV 40"', "Frigobar"],
  },
  {
    id: 102,
    nome: "Quarto Superior",
    descricao: "Espaço ampliado com vista para o jardim, cama king size e banheira.",
    preco: 280,
    tipo: "Superior",
    avaliacao: 9.1,
    imagem: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=600&q=80",
    comodidades: ["Wi-Fi", "Banheira", 'TV 50"', "Varanda"],
  },
  {
    id: 201,
    nome: "Suíte Executiva",
    descricao: "Suíte com sala de estar separada e vista panorâmica da cidade.",
    preco: 420,
    tipo: "Executiva",
    avaliacao: 9.4,
    imagem: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80",
    comodidades: ["Wi-Fi", 'TV 55"', "Sala de estar", "Cofre", "Minibar"],
  },
  {
    id: 301,
    nome: "Suíte Master",
    descricao: "Nossa suíte mais luxuosa com jacuzzi privativa e serviço de mordomo.",
    preco: 750,
    tipo: "Master",
    avaliacao: 9.8,
    imagem: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=600&q=80",
    comodidades: ["Wi-Fi", "Jacuzzi", 'TV 65"', "Varanda", "Mordomo"],
  },
];
